// flow-typed signature: 0f09ccde5986836375c685dcc388f7c2
// flow-typed version: <<STUB>>/avsc_v5.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'avsc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'avsc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'avsc/etc/browser/avsc-protocols' {
  declare module.exports: any;
}

declare module 'avsc/etc/browser/avsc-services' {
  declare module.exports: any;
}

declare module 'avsc/etc/browser/avsc-types' {
  declare module.exports: any;
}

declare module 'avsc/etc/browser/avsc' {
  declare module.exports: any;
}

declare module 'avsc/etc/browser/lib/crypto' {
  declare module.exports: any;
}

declare module 'avsc/etc/browser/lib/files' {
  declare module.exports: any;
}

declare module 'avsc/lib/containers' {
  declare module.exports: any;
}

declare module 'avsc/lib/files' {
  declare module.exports: any;
}

declare module 'avsc/lib/index' {
  declare module.exports: any;
}

declare module 'avsc/lib/services' {
  declare module.exports: any;
}

declare module 'avsc/lib/specs' {
  declare module.exports: any;
}

declare module 'avsc/lib/types' {
  declare module.exports: any;
}

declare module 'avsc/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'avsc/etc/browser/avsc-protocols.js' {
  declare module.exports: $Exports<'avsc/etc/browser/avsc-protocols'>;
}
declare module 'avsc/etc/browser/avsc-services.js' {
  declare module.exports: $Exports<'avsc/etc/browser/avsc-services'>;
}
declare module 'avsc/etc/browser/avsc-types.js' {
  declare module.exports: $Exports<'avsc/etc/browser/avsc-types'>;
}
declare module 'avsc/etc/browser/avsc.js' {
  declare module.exports: $Exports<'avsc/etc/browser/avsc'>;
}
declare module 'avsc/etc/browser/lib/crypto.js' {
  declare module.exports: $Exports<'avsc/etc/browser/lib/crypto'>;
}
declare module 'avsc/etc/browser/lib/files.js' {
  declare module.exports: $Exports<'avsc/etc/browser/lib/files'>;
}
declare module 'avsc/lib/containers.js' {
  declare module.exports: $Exports<'avsc/lib/containers'>;
}
declare module 'avsc/lib/files.js' {
  declare module.exports: $Exports<'avsc/lib/files'>;
}
declare module 'avsc/lib/index.js' {
  declare module.exports: $Exports<'avsc/lib/index'>;
}
declare module 'avsc/lib/services.js' {
  declare module.exports: $Exports<'avsc/lib/services'>;
}
declare module 'avsc/lib/specs.js' {
  declare module.exports: $Exports<'avsc/lib/specs'>;
}
declare module 'avsc/lib/types.js' {
  declare module.exports: $Exports<'avsc/lib/types'>;
}
declare module 'avsc/lib/utils.js' {
  declare module.exports: $Exports<'avsc/lib/utils'>;
}
