// flow-typed signature: 651bb061cbc4f01045823f814c8401a6
// flow-typed version: <<STUB>>/boom_v4.3.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'boom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boom/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boom/lib/index.js' {
  declare module.exports: $Exports<'boom/lib/index'>;
}
