// flow-typed signature: 3fd8d4cc03919cf3923d37ec1fe4ecd7
// flow-typed version: <<STUB>>/convict_v3.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'convict'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'convict' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'convict/lib/convict' {
  declare module.exports: any;
}

// Filename aliases
declare module 'convict/lib/convict.js' {
  declare module.exports: $Exports<'convict/lib/convict'>;
}
