// flow-typed signature: 4aab82c5617dc5fd8250750abf9cdb6d
// flow-typed version: <<STUB>>/electrode-csrf-jwt_v1.2.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-csrf-jwt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-csrf-jwt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-csrf-jwt/gulpfile' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-express' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-hapi' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-koa' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/index' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/csrf-express-test' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/csrf-hapi-test' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/csrf-koa-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-csrf-jwt/gulpfile.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/gulpfile'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-express.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-express'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-hapi.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-hapi'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-koa.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-koa'>;
}
declare module 'electrode-csrf-jwt/lib/csrf.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf'>;
}
declare module 'electrode-csrf-jwt/lib/index.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/index'>;
}
declare module 'electrode-csrf-jwt/test/spec/csrf-express-test.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/csrf-express-test'>;
}
declare module 'electrode-csrf-jwt/test/spec/csrf-hapi-test.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/csrf-hapi-test'>;
}
declare module 'electrode-csrf-jwt/test/spec/csrf-koa-test.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/csrf-koa-test'>;
}
