// flow-typed signature: 5e2ea3c79d240347755937a5925fce3b
// flow-typed version: <<STUB>>/electrode-csrf-jwt_vgit+https://github.com/meetup/electrode-csrf-jwt.git#793431729d8fb4ee315f28709f323f198b25d460/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-csrf-jwt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-csrf-jwt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-csrf-jwt/demo/js/csrf-demo' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/demo/server' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/constants' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-express' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-hapi' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-hapi17' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-koa' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/errors' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/get-id-generators' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/hash-token-engine' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/index' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/jwt-token-engine' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/make-cookie-config' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/simple-id-generator' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/csrf-express-test' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/csrf-hapi-test' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/csrf-koa-test' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/csrf.spec' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/hash-token-engine.spec' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/index.spec' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/jwt-token-engine.spec' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/test/spec/token-engine.spec' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/xclap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-csrf-jwt/demo/js/csrf-demo.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/demo/js/csrf-demo'>;
}
declare module 'electrode-csrf-jwt/demo/server.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/demo/server'>;
}
declare module 'electrode-csrf-jwt/lib/constants.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/constants'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-express.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-express'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-hapi.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-hapi'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-hapi17.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-hapi17'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-koa.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-koa'>;
}
declare module 'electrode-csrf-jwt/lib/csrf.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf'>;
}
declare module 'electrode-csrf-jwt/lib/errors.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/errors'>;
}
declare module 'electrode-csrf-jwt/lib/get-id-generators.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/get-id-generators'>;
}
declare module 'electrode-csrf-jwt/lib/hash-token-engine.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/hash-token-engine'>;
}
declare module 'electrode-csrf-jwt/lib/index.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/index'>;
}
declare module 'electrode-csrf-jwt/lib/jwt-token-engine.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/jwt-token-engine'>;
}
declare module 'electrode-csrf-jwt/lib/make-cookie-config.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/make-cookie-config'>;
}
declare module 'electrode-csrf-jwt/lib/simple-id-generator.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/simple-id-generator'>;
}
declare module 'electrode-csrf-jwt/test/spec/csrf-express-test.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/csrf-express-test'>;
}
declare module 'electrode-csrf-jwt/test/spec/csrf-hapi-test.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/csrf-hapi-test'>;
}
declare module 'electrode-csrf-jwt/test/spec/csrf-koa-test.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/csrf-koa-test'>;
}
declare module 'electrode-csrf-jwt/test/spec/csrf.spec.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/csrf.spec'>;
}
declare module 'electrode-csrf-jwt/test/spec/hash-token-engine.spec.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/hash-token-engine.spec'>;
}
declare module 'electrode-csrf-jwt/test/spec/index.spec.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/index.spec'>;
}
declare module 'electrode-csrf-jwt/test/spec/jwt-token-engine.spec.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/jwt-token-engine.spec'>;
}
declare module 'electrode-csrf-jwt/test/spec/token-engine.spec.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/test/spec/token-engine.spec'>;
}
declare module 'electrode-csrf-jwt/xclap.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/xclap'>;
}
