// flow-typed signature: a496b37b23f6c0005830929639989034
// flow-typed version: <<STUB>>/good_v7.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'good'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'good' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'good/lib/index' {
  declare module.exports: any;
}

declare module 'good/lib/monitor' {
  declare module.exports: any;
}

declare module 'good/lib/schema' {
  declare module.exports: any;
}

declare module 'good/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'good/lib/index.js' {
  declare module.exports: $Exports<'good/lib/index'>;
}
declare module 'good/lib/monitor.js' {
  declare module.exports: $Exports<'good/lib/monitor'>;
}
declare module 'good/lib/schema.js' {
  declare module.exports: $Exports<'good/lib/schema'>;
}
declare module 'good/lib/utils.js' {
  declare module.exports: $Exports<'good/lib/utils'>;
}
