// flow-typed signature: 7048346f28334f5956b4c4bd33fec7fa
// flow-typed version: <<STUB>>/good-squeeze_v5.0.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'good-squeeze'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'good-squeeze' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'good-squeeze/lib/index' {
  declare module.exports: any;
}

declare module 'good-squeeze/lib/safe-json' {
  declare module.exports: any;
}

declare module 'good-squeeze/lib/squeeze' {
  declare module.exports: any;
}

// Filename aliases
declare module 'good-squeeze/lib/index.js' {
  declare module.exports: $Exports<'good-squeeze/lib/index'>;
}
declare module 'good-squeeze/lib/safe-json.js' {
  declare module.exports: $Exports<'good-squeeze/lib/safe-json'>;
}
declare module 'good-squeeze/lib/squeeze.js' {
  declare module.exports: $Exports<'good-squeeze/lib/squeeze'>;
}
