// flow-typed signature: d73cad0c71e84e7ab2eaf7826d95bf56
// flow-typed version: <<STUB>>/hapi-pino_v1.6.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hapi-pino'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hapi-pino' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hapi-pino/benchmarks/good' {
  declare module.exports: any;
}

declare module 'hapi-pino/benchmarks/hapi-pino-extreme' {
  declare module.exports: any;
}

declare module 'hapi-pino/benchmarks/hapi-pino-merge-hapi-log' {
  declare module.exports: any;
}

declare module 'hapi-pino/benchmarks/hapi-pino-no-merge-hapi-log' {
  declare module.exports: any;
}

declare module 'hapi-pino/benchmarks/hapi-pino' {
  declare module.exports: any;
}

declare module 'hapi-pino/benchmarks/hapi-pure' {
  declare module.exports: any;
}

declare module 'hapi-pino/example-good' {
  declare module.exports: any;
}

declare module 'hapi-pino/example' {
  declare module.exports: any;
}

declare module 'hapi-pino/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hapi-pino/benchmarks/good.js' {
  declare module.exports: $Exports<'hapi-pino/benchmarks/good'>;
}
declare module 'hapi-pino/benchmarks/hapi-pino-extreme.js' {
  declare module.exports: $Exports<'hapi-pino/benchmarks/hapi-pino-extreme'>;
}
declare module 'hapi-pino/benchmarks/hapi-pino-merge-hapi-log.js' {
  declare module.exports: $Exports<'hapi-pino/benchmarks/hapi-pino-merge-hapi-log'>;
}
declare module 'hapi-pino/benchmarks/hapi-pino-no-merge-hapi-log.js' {
  declare module.exports: $Exports<'hapi-pino/benchmarks/hapi-pino-no-merge-hapi-log'>;
}
declare module 'hapi-pino/benchmarks/hapi-pino.js' {
  declare module.exports: $Exports<'hapi-pino/benchmarks/hapi-pino'>;
}
declare module 'hapi-pino/benchmarks/hapi-pure.js' {
  declare module.exports: $Exports<'hapi-pino/benchmarks/hapi-pure'>;
}
declare module 'hapi-pino/example-good.js' {
  declare module.exports: $Exports<'hapi-pino/example-good'>;
}
declare module 'hapi-pino/example.js' {
  declare module.exports: $Exports<'hapi-pino/example'>;
}
declare module 'hapi-pino/index' {
  declare module.exports: $Exports<'hapi-pino'>;
}
declare module 'hapi-pino/index.js' {
  declare module.exports: $Exports<'hapi-pino'>;
}
declare module 'hapi-pino/test.js' {
  declare module.exports: $Exports<'hapi-pino/test'>;
}
