// flow-typed signature: 9995ff10faf78071a18311e46c4273c8
// flow-typed version: <<STUB>>/hapi_v16.5.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hapi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hapi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hapi/lib/auth' {
  declare module.exports: any;
}

declare module 'hapi/lib/compression' {
  declare module.exports: any;
}

declare module 'hapi/lib/connection' {
  declare module.exports: any;
}

declare module 'hapi/lib/cors' {
  declare module.exports: any;
}

declare module 'hapi/lib/defaults' {
  declare module.exports: any;
}

declare module 'hapi/lib/ext' {
  declare module.exports: any;
}

declare module 'hapi/lib/handler' {
  declare module.exports: any;
}

declare module 'hapi/lib/index' {
  declare module.exports: any;
}

declare module 'hapi/lib/methods' {
  declare module.exports: any;
}

declare module 'hapi/lib/plugin' {
  declare module.exports: any;
}

declare module 'hapi/lib/promises' {
  declare module.exports: any;
}

declare module 'hapi/lib/protect' {
  declare module.exports: any;
}

declare module 'hapi/lib/reply' {
  declare module.exports: any;
}

declare module 'hapi/lib/request' {
  declare module.exports: any;
}

declare module 'hapi/lib/response' {
  declare module.exports: any;
}

declare module 'hapi/lib/route' {
  declare module.exports: any;
}

declare module 'hapi/lib/schema' {
  declare module.exports: any;
}

declare module 'hapi/lib/server' {
  declare module.exports: any;
}

declare module 'hapi/lib/streams' {
  declare module.exports: any;
}

declare module 'hapi/lib/transmit' {
  declare module.exports: any;
}

declare module 'hapi/lib/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hapi/lib/auth.js' {
  declare module.exports: $Exports<'hapi/lib/auth'>;
}
declare module 'hapi/lib/compression.js' {
  declare module.exports: $Exports<'hapi/lib/compression'>;
}
declare module 'hapi/lib/connection.js' {
  declare module.exports: $Exports<'hapi/lib/connection'>;
}
declare module 'hapi/lib/cors.js' {
  declare module.exports: $Exports<'hapi/lib/cors'>;
}
declare module 'hapi/lib/defaults.js' {
  declare module.exports: $Exports<'hapi/lib/defaults'>;
}
declare module 'hapi/lib/ext.js' {
  declare module.exports: $Exports<'hapi/lib/ext'>;
}
declare module 'hapi/lib/handler.js' {
  declare module.exports: $Exports<'hapi/lib/handler'>;
}
declare module 'hapi/lib/index.js' {
  declare module.exports: $Exports<'hapi/lib/index'>;
}
declare module 'hapi/lib/methods.js' {
  declare module.exports: $Exports<'hapi/lib/methods'>;
}
declare module 'hapi/lib/plugin.js' {
  declare module.exports: $Exports<'hapi/lib/plugin'>;
}
declare module 'hapi/lib/promises.js' {
  declare module.exports: $Exports<'hapi/lib/promises'>;
}
declare module 'hapi/lib/protect.js' {
  declare module.exports: $Exports<'hapi/lib/protect'>;
}
declare module 'hapi/lib/reply.js' {
  declare module.exports: $Exports<'hapi/lib/reply'>;
}
declare module 'hapi/lib/request.js' {
  declare module.exports: $Exports<'hapi/lib/request'>;
}
declare module 'hapi/lib/response.js' {
  declare module.exports: $Exports<'hapi/lib/response'>;
}
declare module 'hapi/lib/route.js' {
  declare module.exports: $Exports<'hapi/lib/route'>;
}
declare module 'hapi/lib/schema.js' {
  declare module.exports: $Exports<'hapi/lib/schema'>;
}
declare module 'hapi/lib/server.js' {
  declare module.exports: $Exports<'hapi/lib/server'>;
}
declare module 'hapi/lib/streams.js' {
  declare module.exports: $Exports<'hapi/lib/streams'>;
}
declare module 'hapi/lib/transmit.js' {
  declare module.exports: $Exports<'hapi/lib/transmit'>;
}
declare module 'hapi/lib/validation.js' {
  declare module.exports: $Exports<'hapi/lib/validation'>;
}
