// flow-typed signature: 65ed888403c650b4abc2008d8955172c
// flow-typed version: <<STUB>>/idb-keyval_v2.3.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idb-keyval'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'idb-keyval' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'idb-keyval/dist/idb-keyval-min' {
  declare module.exports: any;
}

declare module 'idb-keyval/idb-keyval' {
  declare module.exports: any;
}

// Filename aliases
declare module 'idb-keyval/dist/idb-keyval-min.js' {
  declare module.exports: $Exports<'idb-keyval/dist/idb-keyval-min'>;
}
declare module 'idb-keyval/idb-keyval.js' {
  declare module.exports: $Exports<'idb-keyval/idb-keyval'>;
}
