// flow-typed signature: f989b8f522bfbec64f9fc9103de92a04
// flow-typed version: <<STUB>>/inert_v5.1.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inert/lib/directory' {
  declare module.exports: any;
}

declare module 'inert/lib/etag' {
  declare module.exports: any;
}

declare module 'inert/lib/file' {
  declare module.exports: any;
}

declare module 'inert/lib/fs' {
  declare module.exports: any;
}

declare module 'inert/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inert/lib/directory.js' {
  declare module.exports: $Exports<'inert/lib/directory'>;
}
declare module 'inert/lib/etag.js' {
  declare module.exports: $Exports<'inert/lib/etag'>;
}
declare module 'inert/lib/file.js' {
  declare module.exports: $Exports<'inert/lib/file'>;
}
declare module 'inert/lib/fs.js' {
  declare module.exports: $Exports<'inert/lib/fs'>;
}
declare module 'inert/lib/index.js' {
  declare module.exports: $Exports<'inert/lib/index'>;
}
