// flow-typed signature: 5cbf5855bdb75d8690d6d6d5a324cb59
// flow-typed version: <<STUB>>/iron_v4.0.5/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iron/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iron/lib/index.js' {
  declare module.exports: $Exports<'iron/lib/index'>;
}
