// flow-typed signature: e91eb53e91462cae1b9d6d8d51193a87
// flow-typed version: <<STUB>>/iron_v4.0.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'iron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iron/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iron/lib/index.js' {
  declare module.exports: $Exports<'iron/lib/index'>;
}
