// flow-typed signature: a20d4a42bec079257b9905cd6bdbfc13
// flow-typed version: <<STUB>>/js-joda-timezone_v2.0.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-joda-timezone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-joda-timezone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-joda-timezone/dist/js-joda-timezone-empty' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/dist/js-joda-timezone-empty.min' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/dist/js-joda-timezone' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/dist/js-joda-timezone.min' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/auto-plug' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/js-joda-timezone-empty' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/js-joda-timezone' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/license-preamble' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/MomentZoneRules' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/MomentZoneRulesProvider' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/plug' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/system-default-zone' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/tzdbData' {
  declare module.exports: any;
}

declare module 'js-joda-timezone/src/unpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-joda-timezone/dist/js-joda-timezone-empty.js' {
  declare module.exports: $Exports<'js-joda-timezone/dist/js-joda-timezone-empty'>;
}
declare module 'js-joda-timezone/dist/js-joda-timezone-empty.min.js' {
  declare module.exports: $Exports<'js-joda-timezone/dist/js-joda-timezone-empty.min'>;
}
declare module 'js-joda-timezone/dist/js-joda-timezone.js' {
  declare module.exports: $Exports<'js-joda-timezone/dist/js-joda-timezone'>;
}
declare module 'js-joda-timezone/dist/js-joda-timezone.min.js' {
  declare module.exports: $Exports<'js-joda-timezone/dist/js-joda-timezone.min'>;
}
declare module 'js-joda-timezone/src/auto-plug.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/auto-plug'>;
}
declare module 'js-joda-timezone/src/js-joda-timezone-empty.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/js-joda-timezone-empty'>;
}
declare module 'js-joda-timezone/src/js-joda-timezone.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/js-joda-timezone'>;
}
declare module 'js-joda-timezone/src/license-preamble.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/license-preamble'>;
}
declare module 'js-joda-timezone/src/MomentZoneRules.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/MomentZoneRules'>;
}
declare module 'js-joda-timezone/src/MomentZoneRulesProvider.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/MomentZoneRulesProvider'>;
}
declare module 'js-joda-timezone/src/plug.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/plug'>;
}
declare module 'js-joda-timezone/src/system-default-zone.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/system-default-zone'>;
}
declare module 'js-joda-timezone/src/tzdbData.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/tzdbData'>;
}
declare module 'js-joda-timezone/src/unpack.js' {
  declare module.exports: $Exports<'js-joda-timezone/src/unpack'>;
}
