// flow-typed signature: 0c943caaf7126cb8fc576be696b32368
// flow-typed version: <<STUB>>/mwp-cli_v1.1.130/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mwp-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mwp-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mwp-cli/bin/mope' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/cli' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/build' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/browser' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/server' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/trn' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/vendor' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/run' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/runScripts/_app-server' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/runScripts/_webpack-dev-server' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/runScripts/start-dev' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/tx' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/txCommands/pull' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/txCommands/pushNewContent' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/txCommands/pushTxMaster' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/txCommands/util/__mocks__/transifex' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/txCommands/util/index' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/txCommands/util/index.test' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/babel/index' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/env' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/index' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/locales' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/package' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/paths' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/server/index' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/server/index.test' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/server/util' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/webpack/browserAppConfig' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/webpack/index' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/webpack/prodPlugins' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/webpack/require-loader' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/webpack/rules' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/webpack/serverAppConfig' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/config/webpack/vendorBundlesConfig' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/util/addLocalesOption' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mwp-cli/bin/mope.js' {
  declare module.exports: $Exports<'mwp-cli/bin/mope'>;
}
declare module 'mwp-cli/src/cli.js' {
  declare module.exports: $Exports<'mwp-cli/src/cli'>;
}
declare module 'mwp-cli/src/commands/build.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/build'>;
}
declare module 'mwp-cli/src/commands/buildCommands/browser.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/browser'>;
}
declare module 'mwp-cli/src/commands/buildCommands/server.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/server'>;
}
declare module 'mwp-cli/src/commands/buildCommands/trn.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/trn'>;
}
declare module 'mwp-cli/src/commands/buildCommands/vendor.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/vendor'>;
}
declare module 'mwp-cli/src/commands/run.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/run'>;
}
declare module 'mwp-cli/src/commands/runScripts/_app-server.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/runScripts/_app-server'>;
}
declare module 'mwp-cli/src/commands/runScripts/_webpack-dev-server.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/runScripts/_webpack-dev-server'>;
}
declare module 'mwp-cli/src/commands/runScripts/start-dev.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/runScripts/start-dev'>;
}
declare module 'mwp-cli/src/commands/tx.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/tx'>;
}
declare module 'mwp-cli/src/commands/txCommands/pull.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/txCommands/pull'>;
}
declare module 'mwp-cli/src/commands/txCommands/pushNewContent.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/txCommands/pushNewContent'>;
}
declare module 'mwp-cli/src/commands/txCommands/pushTxMaster.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/txCommands/pushTxMaster'>;
}
declare module 'mwp-cli/src/commands/txCommands/util/__mocks__/transifex.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/txCommands/util/__mocks__/transifex'>;
}
declare module 'mwp-cli/src/commands/txCommands/util/index.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/txCommands/util/index'>;
}
declare module 'mwp-cli/src/commands/txCommands/util/index.test.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/txCommands/util/index.test'>;
}
declare module 'mwp-cli/src/config/babel/index.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/babel/index'>;
}
declare module 'mwp-cli/src/config/env.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/env'>;
}
declare module 'mwp-cli/src/config/index.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/index'>;
}
declare module 'mwp-cli/src/config/locales.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/locales'>;
}
declare module 'mwp-cli/src/config/package.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/package'>;
}
declare module 'mwp-cli/src/config/paths.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/paths'>;
}
declare module 'mwp-cli/src/config/server/index.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/server/index'>;
}
declare module 'mwp-cli/src/config/server/index.test.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/server/index.test'>;
}
declare module 'mwp-cli/src/config/server/util.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/server/util'>;
}
declare module 'mwp-cli/src/config/webpack/browserAppConfig.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/webpack/browserAppConfig'>;
}
declare module 'mwp-cli/src/config/webpack/index.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/webpack/index'>;
}
declare module 'mwp-cli/src/config/webpack/prodPlugins.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/webpack/prodPlugins'>;
}
declare module 'mwp-cli/src/config/webpack/require-loader.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/webpack/require-loader'>;
}
declare module 'mwp-cli/src/config/webpack/rules.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/webpack/rules'>;
}
declare module 'mwp-cli/src/config/webpack/serverAppConfig.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/webpack/serverAppConfig'>;
}
declare module 'mwp-cli/src/config/webpack/vendorBundlesConfig.js' {
  declare module.exports: $Exports<'mwp-cli/src/config/webpack/vendorBundlesConfig'>;
}
declare module 'mwp-cli/src/util/addLocalesOption.js' {
  declare module.exports: $Exports<'mwp-cli/src/util/addLocalesOption'>;
}
