// flow-typed signature: 00de194605fdc689b6651d709edcca48
// flow-typed version: <<STUB>>/mwp-test-utils_v>=0.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mwp-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mwp-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mwp-test-utils/__mocks__/styleModule' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/__mocks__/StyleWith' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/lib/index' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/lib/mockApp' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/lib/mockAsyncRoute' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/lib/MockContainer' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/lib/mocks' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/src/index' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/src/mockApp' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/src/mockAsyncRoute' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/src/MockContainer' {
  declare module.exports: any;
}

declare module 'mwp-test-utils/src/mocks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mwp-test-utils/__mocks__/styleModule.js' {
  declare module.exports: $Exports<'mwp-test-utils/__mocks__/styleModule'>;
}
declare module 'mwp-test-utils/__mocks__/StyleWith.jsx' {
  declare module.exports: $Exports<'mwp-test-utils/__mocks__/StyleWith'>;
}
declare module 'mwp-test-utils/lib/index.js' {
  declare module.exports: $Exports<'mwp-test-utils/lib/index'>;
}
declare module 'mwp-test-utils/lib/mockApp.js' {
  declare module.exports: $Exports<'mwp-test-utils/lib/mockApp'>;
}
declare module 'mwp-test-utils/lib/mockAsyncRoute.js' {
  declare module.exports: $Exports<'mwp-test-utils/lib/mockAsyncRoute'>;
}
declare module 'mwp-test-utils/lib/MockContainer.js' {
  declare module.exports: $Exports<'mwp-test-utils/lib/MockContainer'>;
}
declare module 'mwp-test-utils/lib/mocks.js' {
  declare module.exports: $Exports<'mwp-test-utils/lib/mocks'>;
}
declare module 'mwp-test-utils/src/index.js' {
  declare module.exports: $Exports<'mwp-test-utils/src/index'>;
}
declare module 'mwp-test-utils/src/mockApp.jsx' {
  declare module.exports: $Exports<'mwp-test-utils/src/mockApp'>;
}
declare module 'mwp-test-utils/src/mockAsyncRoute.js' {
  declare module.exports: $Exports<'mwp-test-utils/src/mockAsyncRoute'>;
}
declare module 'mwp-test-utils/src/MockContainer.jsx' {
  declare module.exports: $Exports<'mwp-test-utils/src/MockContainer'>;
}
declare module 'mwp-test-utils/src/mocks.js' {
  declare module.exports: $Exports<'mwp-test-utils/src/mocks'>;
}
