// flow-typed signature: 8e9d70dc2950810b98d651e69932e0fc
// flow-typed version: <<STUB>>/mwp-router_v>=0.0.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mwp-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mwp-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mwp-router/lib/AsyncRoute' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/Forbidden' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/forbidden.test' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/index' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/Link' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/link.test' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/NotFound' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/Redirect' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/redirect.test' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/reducer' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/routeActionCreators' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/RouteLayout' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/SyncContainer' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/types' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/util/index' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/util/matcher' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/util/matcher.test' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/util/query' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/util/query.test' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/util/resolve' {
  declare module.exports: any;
}

declare module 'mwp-router/lib/util/resolve.test' {
  declare module.exports: any;
}

declare module 'mwp-router/src/AsyncRoute' {
  declare module.exports: any;
}

declare module 'mwp-router/src/Forbidden' {
  declare module.exports: any;
}

declare module 'mwp-router/src/forbidden.test' {
  declare module.exports: any;
}

declare module 'mwp-router/src/index' {
  declare module.exports: any;
}

declare module 'mwp-router/src/Link' {
  declare module.exports: any;
}

declare module 'mwp-router/src/link.test' {
  declare module.exports: any;
}

declare module 'mwp-router/src/NotFound' {
  declare module.exports: any;
}

declare module 'mwp-router/src/Redirect' {
  declare module.exports: any;
}

declare module 'mwp-router/src/redirect.test' {
  declare module.exports: any;
}

declare module 'mwp-router/src/reducer' {
  declare module.exports: any;
}

declare module 'mwp-router/src/routeActionCreators' {
  declare module.exports: any;
}

declare module 'mwp-router/src/RouteLayout' {
  declare module.exports: any;
}

declare module 'mwp-router/src/SyncContainer' {
  declare module.exports: any;
}

declare module 'mwp-router/src/types' {
  declare module.exports: any;
}

declare module 'mwp-router/src/util/index' {
  declare module.exports: any;
}

declare module 'mwp-router/src/util/matcher' {
  declare module.exports: any;
}

declare module 'mwp-router/src/util/matcher.test' {
  declare module.exports: any;
}

declare module 'mwp-router/src/util/query' {
  declare module.exports: any;
}

declare module 'mwp-router/src/util/query.test' {
  declare module.exports: any;
}

declare module 'mwp-router/src/util/resolve' {
  declare module.exports: any;
}

declare module 'mwp-router/src/util/resolve.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mwp-router/lib/AsyncRoute.js' {
  declare module.exports: $Exports<'mwp-router/lib/AsyncRoute'>;
}
declare module 'mwp-router/lib/Forbidden.js' {
  declare module.exports: $Exports<'mwp-router/lib/Forbidden'>;
}
declare module 'mwp-router/lib/forbidden.test.js' {
  declare module.exports: $Exports<'mwp-router/lib/forbidden.test'>;
}
declare module 'mwp-router/lib/index.js' {
  declare module.exports: $Exports<'mwp-router/lib/index'>;
}
declare module 'mwp-router/lib/Link.js' {
  declare module.exports: $Exports<'mwp-router/lib/Link'>;
}
declare module 'mwp-router/lib/link.test.js' {
  declare module.exports: $Exports<'mwp-router/lib/link.test'>;
}
declare module 'mwp-router/lib/NotFound.js' {
  declare module.exports: $Exports<'mwp-router/lib/NotFound'>;
}
declare module 'mwp-router/lib/Redirect.js' {
  declare module.exports: $Exports<'mwp-router/lib/Redirect'>;
}
declare module 'mwp-router/lib/redirect.test.js' {
  declare module.exports: $Exports<'mwp-router/lib/redirect.test'>;
}
declare module 'mwp-router/lib/reducer.js' {
  declare module.exports: $Exports<'mwp-router/lib/reducer'>;
}
declare module 'mwp-router/lib/routeActionCreators.js' {
  declare module.exports: $Exports<'mwp-router/lib/routeActionCreators'>;
}
declare module 'mwp-router/lib/RouteLayout.js' {
  declare module.exports: $Exports<'mwp-router/lib/RouteLayout'>;
}
declare module 'mwp-router/lib/SyncContainer.js' {
  declare module.exports: $Exports<'mwp-router/lib/SyncContainer'>;
}
declare module 'mwp-router/lib/types.js' {
  declare module.exports: $Exports<'mwp-router/lib/types'>;
}
declare module 'mwp-router/lib/util/index.js' {
  declare module.exports: $Exports<'mwp-router/lib/util/index'>;
}
declare module 'mwp-router/lib/util/matcher.js' {
  declare module.exports: $Exports<'mwp-router/lib/util/matcher'>;
}
declare module 'mwp-router/lib/util/matcher.test.js' {
  declare module.exports: $Exports<'mwp-router/lib/util/matcher.test'>;
}
declare module 'mwp-router/lib/util/query.js' {
  declare module.exports: $Exports<'mwp-router/lib/util/query'>;
}
declare module 'mwp-router/lib/util/query.test.js' {
  declare module.exports: $Exports<'mwp-router/lib/util/query.test'>;
}
declare module 'mwp-router/lib/util/resolve.js' {
  declare module.exports: $Exports<'mwp-router/lib/util/resolve'>;
}
declare module 'mwp-router/lib/util/resolve.test.js' {
  declare module.exports: $Exports<'mwp-router/lib/util/resolve.test'>;
}
declare module 'mwp-router/src/AsyncRoute.jsx' {
  declare module.exports: $Exports<'mwp-router/src/AsyncRoute'>;
}
declare module 'mwp-router/src/Forbidden.jsx' {
  declare module.exports: $Exports<'mwp-router/src/Forbidden'>;
}
declare module 'mwp-router/src/forbidden.test.jsx' {
  declare module.exports: $Exports<'mwp-router/src/forbidden.test'>;
}
declare module 'mwp-router/src/index.js' {
  declare module.exports: $Exports<'mwp-router/src/index'>;
}
declare module 'mwp-router/src/Link.jsx' {
  declare module.exports: $Exports<'mwp-router/src/Link'>;
}
declare module 'mwp-router/src/link.test.jsx' {
  declare module.exports: $Exports<'mwp-router/src/link.test'>;
}
declare module 'mwp-router/src/NotFound.jsx' {
  declare module.exports: $Exports<'mwp-router/src/NotFound'>;
}
declare module 'mwp-router/src/Redirect.jsx' {
  declare module.exports: $Exports<'mwp-router/src/Redirect'>;
}
declare module 'mwp-router/src/redirect.test.jsx' {
  declare module.exports: $Exports<'mwp-router/src/redirect.test'>;
}
declare module 'mwp-router/src/reducer.js' {
  declare module.exports: $Exports<'mwp-router/src/reducer'>;
}
declare module 'mwp-router/src/routeActionCreators.js' {
  declare module.exports: $Exports<'mwp-router/src/routeActionCreators'>;
}
declare module 'mwp-router/src/RouteLayout.jsx' {
  declare module.exports: $Exports<'mwp-router/src/RouteLayout'>;
}
declare module 'mwp-router/src/SyncContainer.jsx' {
  declare module.exports: $Exports<'mwp-router/src/SyncContainer'>;
}
declare module 'mwp-router/src/types.js' {
  declare module.exports: $Exports<'mwp-router/src/types'>;
}
declare module 'mwp-router/src/util/index.js' {
  declare module.exports: $Exports<'mwp-router/src/util/index'>;
}
declare module 'mwp-router/src/util/matcher.js' {
  declare module.exports: $Exports<'mwp-router/src/util/matcher'>;
}
declare module 'mwp-router/src/util/matcher.test.jsx' {
  declare module.exports: $Exports<'mwp-router/src/util/matcher.test'>;
}
declare module 'mwp-router/src/util/query.js' {
  declare module.exports: $Exports<'mwp-router/src/util/query'>;
}
declare module 'mwp-router/src/util/query.test.js' {
  declare module.exports: $Exports<'mwp-router/src/util/query.test'>;
}
declare module 'mwp-router/src/util/resolve.js' {
  declare module.exports: $Exports<'mwp-router/src/util/resolve'>;
}
declare module 'mwp-router/src/util/resolve.test.jsx' {
  declare module.exports: $Exports<'mwp-router/src/util/resolve.test'>;
}
