// flow-typed signature: d9419eccaf0aeb600d27a4563ed48acf
// flow-typed version: <<STUB>>/mwp-cli_v0.1.33/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mwp-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mwp-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mwp-cli/bin/mope' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/cli' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/build' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/browser' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/env' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/index' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/locales' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/paths' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/webpack/browserAppConfig' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/webpack/index' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/webpack/prodPlugins' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/webpack/require-loader' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/webpack/serverAppConfig' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/config/webpack/vendorBundlesConfig' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/server' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/buildCommands/vendor' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/run' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/runScripts/_app-server' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/runScripts/_webpack-dev-server' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/commands/runScripts/start-dev' {
  declare module.exports: any;
}

declare module 'mwp-cli/src/util/supportedLocales' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mwp-cli/bin/mope.js' {
  declare module.exports: $Exports<'mwp-cli/bin/mope'>;
}
declare module 'mwp-cli/src/cli.js' {
  declare module.exports: $Exports<'mwp-cli/src/cli'>;
}
declare module 'mwp-cli/src/commands/build.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/build'>;
}
declare module 'mwp-cli/src/commands/buildCommands/browser.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/browser'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/env.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/env'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/index.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/index'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/locales.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/locales'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/paths.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/paths'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/webpack/browserAppConfig.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/webpack/browserAppConfig'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/webpack/index.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/webpack/index'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/webpack/prodPlugins.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/webpack/prodPlugins'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/webpack/require-loader.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/webpack/require-loader'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/webpack/serverAppConfig.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/webpack/serverAppConfig'>;
}
declare module 'mwp-cli/src/commands/buildCommands/config/webpack/vendorBundlesConfig.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/config/webpack/vendorBundlesConfig'>;
}
declare module 'mwp-cli/src/commands/buildCommands/server.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/server'>;
}
declare module 'mwp-cli/src/commands/buildCommands/vendor.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/buildCommands/vendor'>;
}
declare module 'mwp-cli/src/commands/run.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/run'>;
}
declare module 'mwp-cli/src/commands/runScripts/_app-server.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/runScripts/_app-server'>;
}
declare module 'mwp-cli/src/commands/runScripts/_webpack-dev-server.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/runScripts/_webpack-dev-server'>;
}
declare module 'mwp-cli/src/commands/runScripts/start-dev.js' {
  declare module.exports: $Exports<'mwp-cli/src/commands/runScripts/start-dev'>;
}
declare module 'mwp-cli/src/util/supportedLocales.js' {
  declare module.exports: $Exports<'mwp-cli/src/util/supportedLocales'>;
}
