// flow-typed signature: 04eef20ae375b3cb34967cfa5cb5c39b
// flow-typed version: <<STUB>>/pino_v4.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pino'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pino' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pino/bin' {
  declare module.exports: any;
}

declare module 'pino/browser' {
  declare module.exports: any;
}

declare module 'pino/example' {
  declare module.exports: any;
}

declare module 'pino/lib/events' {
  declare module.exports: any;
}

declare module 'pino/lib/levels' {
  declare module.exports: any;
}

declare module 'pino/lib/serializers' {
  declare module.exports: any;
}

declare module 'pino/lib/time' {
  declare module.exports: any;
}

declare module 'pino/lib/tools' {
  declare module.exports: any;
}

declare module 'pino/pino' {
  declare module.exports: any;
}

declare module 'pino/pretty' {
  declare module.exports: any;
}

declare module 'pino/test/addlevel.test' {
  declare module.exports: any;
}

declare module 'pino/test/basic.test' {
  declare module.exports: any;
}

declare module 'pino/test/browser.test' {
  declare module.exports: any;
}

declare module 'pino/test/error.test' {
  declare module.exports: any;
}

declare module 'pino/test/escaping.test' {
  declare module.exports: any;
}

declare module 'pino/test/events.test' {
  declare module.exports: any;
}

declare module 'pino/test/extreme.test' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/events/no-event-loop' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/events/no-fd' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/events/sighup-no-handler' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/events/sighup-with-handler' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/events/uncaughtException-noTerminate' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/events/uncaughtException' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/extreme_child' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/extreme' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/basic' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/levelFirst' {
  declare module.exports: any;
}

declare module 'pino/test/helper' {
  declare module.exports: any;
}

declare module 'pino/test/http.test' {
  declare module.exports: any;
}

declare module 'pino/test/levels.test' {
  declare module.exports: any;
}

declare module 'pino/test/metadata.test' {
  declare module.exports: any;
}

declare module 'pino/test/pretty.test' {
  declare module.exports: any;
}

declare module 'pino/test/serializers.test' {
  declare module.exports: any;
}

declare module 'pino/test/timestamp.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pino/bin.js' {
  declare module.exports: $Exports<'pino/bin'>;
}
declare module 'pino/browser.js' {
  declare module.exports: $Exports<'pino/browser'>;
}
declare module 'pino/example.js' {
  declare module.exports: $Exports<'pino/example'>;
}
declare module 'pino/lib/events.js' {
  declare module.exports: $Exports<'pino/lib/events'>;
}
declare module 'pino/lib/levels.js' {
  declare module.exports: $Exports<'pino/lib/levels'>;
}
declare module 'pino/lib/serializers.js' {
  declare module.exports: $Exports<'pino/lib/serializers'>;
}
declare module 'pino/lib/time.js' {
  declare module.exports: $Exports<'pino/lib/time'>;
}
declare module 'pino/lib/tools.js' {
  declare module.exports: $Exports<'pino/lib/tools'>;
}
declare module 'pino/pino.js' {
  declare module.exports: $Exports<'pino/pino'>;
}
declare module 'pino/pretty.js' {
  declare module.exports: $Exports<'pino/pretty'>;
}
declare module 'pino/test/addlevel.test.js' {
  declare module.exports: $Exports<'pino/test/addlevel.test'>;
}
declare module 'pino/test/basic.test.js' {
  declare module.exports: $Exports<'pino/test/basic.test'>;
}
declare module 'pino/test/browser.test.js' {
  declare module.exports: $Exports<'pino/test/browser.test'>;
}
declare module 'pino/test/error.test.js' {
  declare module.exports: $Exports<'pino/test/error.test'>;
}
declare module 'pino/test/escaping.test.js' {
  declare module.exports: $Exports<'pino/test/escaping.test'>;
}
declare module 'pino/test/events.test.js' {
  declare module.exports: $Exports<'pino/test/events.test'>;
}
declare module 'pino/test/extreme.test.js' {
  declare module.exports: $Exports<'pino/test/extreme.test'>;
}
declare module 'pino/test/fixtures/events/no-event-loop.js' {
  declare module.exports: $Exports<'pino/test/fixtures/events/no-event-loop'>;
}
declare module 'pino/test/fixtures/events/no-fd.js' {
  declare module.exports: $Exports<'pino/test/fixtures/events/no-fd'>;
}
declare module 'pino/test/fixtures/events/sighup-no-handler.js' {
  declare module.exports: $Exports<'pino/test/fixtures/events/sighup-no-handler'>;
}
declare module 'pino/test/fixtures/events/sighup-with-handler.js' {
  declare module.exports: $Exports<'pino/test/fixtures/events/sighup-with-handler'>;
}
declare module 'pino/test/fixtures/events/uncaughtException-noTerminate.js' {
  declare module.exports: $Exports<'pino/test/fixtures/events/uncaughtException-noTerminate'>;
}
declare module 'pino/test/fixtures/events/uncaughtException.js' {
  declare module.exports: $Exports<'pino/test/fixtures/events/uncaughtException'>;
}
declare module 'pino/test/fixtures/extreme_child.js' {
  declare module.exports: $Exports<'pino/test/fixtures/extreme_child'>;
}
declare module 'pino/test/fixtures/extreme.js' {
  declare module.exports: $Exports<'pino/test/fixtures/extreme'>;
}
declare module 'pino/test/fixtures/pretty/basic.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/basic'>;
}
declare module 'pino/test/fixtures/pretty/levelFirst.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/levelFirst'>;
}
declare module 'pino/test/helper.js' {
  declare module.exports: $Exports<'pino/test/helper'>;
}
declare module 'pino/test/http.test.js' {
  declare module.exports: $Exports<'pino/test/http.test'>;
}
declare module 'pino/test/levels.test.js' {
  declare module.exports: $Exports<'pino/test/levels.test'>;
}
declare module 'pino/test/metadata.test.js' {
  declare module.exports: $Exports<'pino/test/metadata.test'>;
}
declare module 'pino/test/pretty.test.js' {
  declare module.exports: $Exports<'pino/test/pretty.test'>;
}
declare module 'pino/test/serializers.test.js' {
  declare module.exports: $Exports<'pino/test/serializers.test'>;
}
declare module 'pino/test/timestamp.test.js' {
  declare module.exports: $Exports<'pino/test/timestamp.test'>;
}
