// flow-typed signature: 3c54b964c56e16fd9d6f5a4af78707e8
// flow-typed version: <<STUB>>/react-side-effect_v1.1.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-side-effect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-side-effect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-side-effect/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-side-effect/lib/index.js' {
  declare module.exports: $Exports<'react-side-effect/lib/index'>;
}
