// flow-typed signature: 567727cf5b5f8293f18c8c27e719c1e1
// flow-typed version: <<STUB>>/rison_v0.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rison'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rison' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rison/js/rison' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rison/js/rison.js' {
  declare module.exports: $Exports<'rison/js/rison'>;
}
