// flow-typed signature: e500c066cc97ccd642ef4f5741bbff8e
// flow-typed version: <<STUB>>/spdy_v3.4.7/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spdy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spdy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spdy/lib/spdy' {
  declare module.exports: any;
}

declare module 'spdy/lib/spdy/agent' {
  declare module.exports: any;
}

declare module 'spdy/lib/spdy/handle' {
  declare module.exports: any;
}

declare module 'spdy/lib/spdy/request' {
  declare module.exports: any;
}

declare module 'spdy/lib/spdy/response' {
  declare module.exports: any;
}

declare module 'spdy/lib/spdy/server' {
  declare module.exports: any;
}

declare module 'spdy/lib/spdy/socket' {
  declare module.exports: any;
}

declare module 'spdy/test/client-test' {
  declare module.exports: any;
}

declare module 'spdy/test/fixtures' {
  declare module.exports: any;
}

declare module 'spdy/test/server-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spdy/lib/spdy.js' {
  declare module.exports: $Exports<'spdy/lib/spdy'>;
}
declare module 'spdy/lib/spdy/agent.js' {
  declare module.exports: $Exports<'spdy/lib/spdy/agent'>;
}
declare module 'spdy/lib/spdy/handle.js' {
  declare module.exports: $Exports<'spdy/lib/spdy/handle'>;
}
declare module 'spdy/lib/spdy/request.js' {
  declare module.exports: $Exports<'spdy/lib/spdy/request'>;
}
declare module 'spdy/lib/spdy/response.js' {
  declare module.exports: $Exports<'spdy/lib/spdy/response'>;
}
declare module 'spdy/lib/spdy/server.js' {
  declare module.exports: $Exports<'spdy/lib/spdy/server'>;
}
declare module 'spdy/lib/spdy/socket.js' {
  declare module.exports: $Exports<'spdy/lib/spdy/socket'>;
}
declare module 'spdy/test/client-test.js' {
  declare module.exports: $Exports<'spdy/test/client-test'>;
}
declare module 'spdy/test/fixtures.js' {
  declare module.exports: $Exports<'spdy/test/fixtures'>;
}
declare module 'spdy/test/server-test.js' {
  declare module.exports: $Exports<'spdy/test/server-test'>;
}
