// run directly by node, no babel
const startServer = require('mwp-app-server').default;

/**
 * special route for root request for favicon
 * @return {Object} the route for the favicon
 */

const routes = [
	{
		method: 'GET',
		path: '/favicon.ico',
		options: {
			auth: false,
		},
		handler: (request, h) => 'favicon',
	},
	{
		method: 'GET',
		path: `/app.js`,
		options: {
			auth: false,
			cache: {
				expiresIn: 1000 * 60 * 60 * 24 * 365, // one year
			},
		},
		handler: (request, h) => '',
	},
];
/**
 * The actual configure-and-start function. Sets up the arguments for the
 * platform `startServer` function. The map of localeCodes to server-app
 * rendering functions can be suppled directly as an argument, or read from
 * the default generated module in build/server-app/serverAppMap
 *
 * @param {Object} appMap (optional) a map of locale codes to server rendering
 *   functions. Defaults to the appMap generated by `make build-server`
 * @return {Promise} a Promise that returns the started server
 */
module.exports = function main(appMap) {
	if (!appMap) {
		throw new Error('No map of localeCode to renderer provided');
	}

	const plugins = []; // for serving the favicon

	return startServer(appMap, { routes, plugins }).catch(err => {
		// catch because otherwise Node swallows errors in Promises
		throw err;
	});
};
