// flow-typed signature: d03d98b5c7786aa8421858abf0da753d
// flow-typed version: <<STUB>>/@google-cloud/pubsub_v0.13.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google-cloud/pubsub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google-cloud/pubsub' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google-cloud/pubsub/src/iam' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/index' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/snapshot' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/subscription' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/topic' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/v1/doc/doc_google_protobuf_duration' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/v1/doc/doc_google_protobuf_field_mask' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/v1/doc/doc_google_protobuf_timestamp' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/v1/doc/doc_pubsub' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/v1/index' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/v1/publisher_client' {
  declare module.exports: any;
}

declare module '@google-cloud/pubsub/src/v1/subscriber_client' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google-cloud/pubsub/src/iam.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/iam'>;
}
declare module '@google-cloud/pubsub/src/index.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/index'>;
}
declare module '@google-cloud/pubsub/src/snapshot.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/snapshot'>;
}
declare module '@google-cloud/pubsub/src/subscription.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/subscription'>;
}
declare module '@google-cloud/pubsub/src/topic.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/topic'>;
}
declare module '@google-cloud/pubsub/src/v1/doc/doc_google_protobuf_duration.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/v1/doc/doc_google_protobuf_duration'>;
}
declare module '@google-cloud/pubsub/src/v1/doc/doc_google_protobuf_field_mask.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/v1/doc/doc_google_protobuf_field_mask'>;
}
declare module '@google-cloud/pubsub/src/v1/doc/doc_google_protobuf_timestamp.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/v1/doc/doc_google_protobuf_timestamp'>;
}
declare module '@google-cloud/pubsub/src/v1/doc/doc_pubsub.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/v1/doc/doc_pubsub'>;
}
declare module '@google-cloud/pubsub/src/v1/index.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/v1/index'>;
}
declare module '@google-cloud/pubsub/src/v1/publisher_client.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/v1/publisher_client'>;
}
declare module '@google-cloud/pubsub/src/v1/subscriber_client.js' {
  declare module.exports: $Exports<'@google-cloud/pubsub/src/v1/subscriber_client'>;
}
